### ISSUE TITLE
Adding new vertex to existing graph?

### ISSUE THREAD

**Issue by cxw42** [chen0040/lua-graph#1]
Thank you for developing this library!  I will be building a graph iteratively, and I do not know the number of vertices in advance.  I have looked at the README and the source, and I do not see a way.  Is it possible to add a vertex after the call to `data.graph.create()`?  If not, would you be willing to add that function?  I appreciate your considering this request!

**Comment by chen0040** [comment]
Thanks for your suggestion, this should be no problem, I will add that function in these two days and update you again :)

**Comment by chen0040** [comment]
Hi @cxw42 I have updated the library to include api that allows the graph to be expand and shrink such as 

- graph:addVertexIfNotExists(vertexId), 
- graph:removeVertex(vertexId), 
- graph:vertexCount(), 
- graph:vertexAt(vertexIndex),
- graph:addEdge(vertexId1, vertexId2, ...) (addEdge is changed so that if the vertices in its parameters do not exists in the graph, they will be automatically added to the graph)

Please refers to the section "Create an undirected unweighted graph and add / remove vertices later" and "Create an undirected unweighted graph from a list of vertices and expand or shrink it". the operations apply to the different types of graphs as well. the there are also unit testing results in the graph_spec.lua. 

Note that the graph.V is removed and replaced with graph:vertexCount() and graph:vertexAt(index) method for iterating all vertices (this change was introduced so that graph vertices do not need to start with vertex 0 and do not need to be consecutive. Please let me know if there are problems using the updated version :)
